### ISSUE TITLE
Running bootstrap.js inserts ?????? instead of Hebrew

### ISSUE THREAD

**Issue by forforeach** [EladRK/EfoZol#2]
![capture](https://cloud.githubusercontent.com/assets/2650168/8024197/a040c438-0d33-11e5-8b98-5ace0a0749ba.PNG)

**Comment by benjamingr** [comment]
This smells like an encoding issue. If you insert a document to Mongo manually does it work?

(That is: run `mongo` type `use efozol1` and then `db.products.insert({name: "חלב", price: 10})`)

**Comment by forforeach** [comment]
Thanks, it's my freaking cmd :-)
